### ISSUE TITLE
能不能rss啊？

### ISSUE THREAD

**Issue by zhl111** [QuietKnightLegion/sound-of-silence#1]
希望能订阅

**Comment by QuietKnightLegion** [comment]
VitePress 是偏向静态文档的框架，不提供 RSS 功能。
网站内容本身也不是日志形式，更像是个档案库。比如新内容通常是编辑已有的一个页面，而不是发布一篇新文章。

感谢你的建议，如果未来增加类似更新日志的东西会再考虑开放订阅。
